"use client";
import { useQuery } from "@tanstack/react-query";
import { useToken } from "@/lib/auth-context";
import { getDashboard } from "@/services/dashboard.service";
import { getSignals } from "@/services/signals.service";
import { getRecommendations } from "@/services/recommendations.service";
import { MetricCard } from "@/components/dashboard/metric-card";
import { PriorityList } from "@/components/dashboard/priority-list";
import { SignalSummary } from "@/components/dashboard/signal-summary";
import { PageHeader } from "@/components/layout/page-header";
import { money } from "@/lib/utils";
export function DashboardView() { const token = useToken(); const dashboard = useQuery({ queryKey: ["dashboard"], queryFn: async () => getDashboard(await token()) }); const signals = useQuery({ queryKey: ["signals"], queryFn: async () => getSignals(await token()) }); const recommendations=useQuery({queryKey:["recommendations"],queryFn:async()=>getRecommendations(await token())}); if (dashboard.isLoading) return <div className="empty">Loading operational summary…</div>; if (dashboard.isError || !dashboard.data) return <div className="empty">Could not load dashboard.</div>; const x = dashboard.data; return <><PageHeader title="Overview" description="Operational risks and decisions, updated from business data." /><div className="grid-cards"><MetricCard label="Revenue · 30 days" value={money(x.revenue_30d)} /><MetricCard label="Outstanding" value={money(x.outstanding)} /><MetricCard label="Overdue" value={money(x.overdue)} /><MetricCard label="Low stock" value={String(x.low_stock)} /><MetricCard label="Critical alerts" value={String(x.critical_alerts)} /><MetricCard label="Pending actions" value={String(x.pending_actions)} /></div><div className="section-grid"><section className="card section-card"><h2 className="section-title">Today&apos;s priorities</h2><PriorityList items={x.priorities} /></section><section className="card section-card"><h2 className="section-title">Active risks by area</h2><SignalSummary signals={signals.data?.items ?? []} /></section></div><section className="card section-card" style={{marginTop:16}}><h2 className="section-title">Recent AI recommendations</h2>{recommendations.data?.items.length ? recommendations.data.items.slice(0,3).map(item=><div key={item.id} className="priority-row"><div><div className="priority-title">{item.recommendation.title}</div><div className="priority-desc">{item.recommendation.reason}</div></div></div>) : <div style={{color:"var(--muted)",fontSize:12}}>Ask OpsPilot a reasoning question to generate a grounded recommendation.</div>}</section></>; }
